version: '3'
services:
  prisma1:
    image: prismagraphql/prisma:1.34
    restart: always
    networks:
      - back
    ports:
      - '4467:4467'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4467
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres1:
    image: postgres:10.3
    restart: always
    networks:
      - back
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

  app1: 
   image: eso-build-backend-staging
   networks: 
     - reverse-proxy
     - back
   environment:
     - VIRTUAL_PORT=80
     - VIRTUAL_HOST=eso-build-backend-staging.fewhnhouse.de
     - LETSENCRYPT_HOST=eso-build-backend.staging.fewhnhouse.de
     - LETSENCRYPT_EMAIL=felix.wohnhaas@outlook.com
 
      
volumes:
  postgres: ~

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge

