version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    networks:
      - back
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: ${PRISMA_USER}
            password: ${PRISMA_PASSWORD}
  postgres:
    image: postgres:10.3
    restart: always
    networks:
      - back
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    image: eso-build-backend
    networks:
      - traefik
      - back
    expose:
      - 80
    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - 'traefik.enable=true' # <== Enable traefik to proxy this container
      - 'traefik.http.routers.eso-build-backend-web.rule=Host(`eso-build-backend.fewhnhouse.de`)' # <== Your Domain Name goes here for the http rule
      - 'traefik.http.routers.eso-build-backend-web.entrypoints=web' # <== Defining the entrypoint for http, **ref: line 30
      # - "traefik.http.routers.eso-build-backend-web.middlewares=redirect@file" # <== This is a middleware to redirect to https
      - 'traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true'
      - 'traefik.http.routers.eso-build-backend-secured.rule=Host(`eso-build-backend.fewhnhouse.de`)' # <== Your Domain Name for the https rule
      - 'traefik.http.routers.eso-build-backend-secured.entrypoints=web-secured' # <== Defining entrypoint for https, **ref: line 31
      - 'traefik.http.routers.eso-build-backend-secured.tls.certresolver=mytlschallenge' # <== Defining certsresolvers for https
      - "traefik.docker.network=traefik"

volumes:
  postgres: ~

networks:
  traefik:
    external: true
  back:
    driver: bridge
